# Generated by Django 4.2.2 on 2023-06-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sex',
            field=models.CharField(choices=[('Мужской', 'M'), ('Женский', 'W')], max_length=7, null=True, verbose_name='Пол'),
        ),
    ]
