# Generated by Django 4.2.2 on 2023-06-22 05:18

import api.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Оглавление')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('slug', models.SlugField(default='', unique=True)),
                ('image', models.ImageField(upload_to='banners/images/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='categories/images/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CategoryBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Категория - Баннер',
                'verbose_name_plural': 'Категории - Баннеры',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_full', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Условие',
                'verbose_name_plural': 'Условия',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=70, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('discount', models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Число должно быть положительным', regex='^[0-9.]+$'), api.validators.validate_less_hundred], verbose_name='Скидка')),
                ('calorie', models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Число должно быть положительным', regex='^[0-9.]+$')], verbose_name='Калории')),
                ('proteins', models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Число должно быть положительным', regex='^[0-9.]+$')], verbose_name='Белки')),
                ('fats', models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Число должно быть положительным', regex='^[0-9.]+$')], verbose_name='Жиры')),
                ('carbohydrates', models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Число должно быть положительным', regex='^[0-9.]+$')], verbose_name='Углероды')),
                ('image', models.ImageField(blank=True, upload_to='products/images/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Товар - Категория',
                'verbose_name_plural': 'Товары - Категории',
            },
        ),
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Продукт - Свойство',
                'verbose_name_plural': 'Продукты - Свойства',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(validators=[django.core.validators.RegexValidator(message='Число должно быть положительным', regex='^[0-9.]+$')], verbose_name='Цена')),
                ('weight', models.IntegerField(validators=[django.core.validators.RegexValidator(message='Число должно быть положительным', regex='^[0-9.]+$')], verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Тип товара',
                'verbose_name_plural': 'Типы товаров',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('title', models.CharField(max_length=255, verbose_name='Загаловок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(default='', unique=True)),
                ('hex_color', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Неправильный формат цвета', regex='^#[a-zA-Z0-9]+$')], verbose_name='Цвет акции')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала акции')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата конца акции')),
                ('image', models.ImageField(upload_to='promotions/images/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='PromotionCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Акция - условие',
                'verbose_name_plural': 'Акции - условия',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('slug', models.SlugField(default='', unique=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='properties/images/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Свойство',
                'verbose_name_plural': 'Свойства',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(validators=[django.core.validators.RegexValidator(message='Число должно быть положительным', regex='^[0-9.]+$')], verbose_name='Размер')),
                ('measurement', models.CharField(choices=[('шт', 'T'), ('см', 'C'), ('л', 'L')], max_length=2, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.AddConstraint(
            model_name='size',
            constraint=models.UniqueConstraint(fields=('size', 'measurement'), name='unique_size'),
        ),
        migrations.AddField(
            model_name='promotioncondition',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='api.condition'),
        ),
        migrations.AddField(
            model_name='promotioncondition',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='api.promotion'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='condition',
            field=models.ManyToManyField(through='api.PromotionCondition', to='api.condition'),
        ),
        migrations.AddField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='api.product'),
        ),
        migrations.AddField(
            model_name='productsize',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.size', verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='productproperty',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='api.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='productproperty',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.property', verbose_name='Свойство'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(through='api.ProductCategory', to='api.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.ManyToManyField(through='api.Collection', to='api.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.promotion'),
        ),
        migrations.AddField(
            model_name='product',
            name='property',
            field=models.ManyToManyField(through='api.ProductProperty', to='api.property'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(through='api.ProductSize', to='api.size', verbose_name='Размеры'),
        ),
        migrations.AddField(
            model_name='collection',
            name='child_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='api.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='collection',
            name='parent_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='api.product'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='api.country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='categorybanner',
            name='banner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.banner'),
        ),
        migrations.AddField(
            model_name='categorybanner',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='api.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='banner',
            field=models.ManyToManyField(through='api.CategoryBanner', to='api.banner', verbose_name='Баннер'),
        ),
        migrations.AddConstraint(
            model_name='productproperty',
            constraint=models.UniqueConstraint(fields=('product', 'property'), name='unique_product_property'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('parent_product', 'child_product'), name='unique_collection'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('name', 'country'), name='unique_location'),
        ),
    ]
