# Generated by Django 4.2.2 on 2023-06-16 17:17

import api.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Оглавление')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('slug', models.SlugField(default='', unique=True)),
                ('image', models.ImageField(upload_to='banners/images/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='categories/images/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CategoryBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Категория - Баннер',
                'verbose_name_plural': 'Категории - Баннеры',
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Условие',
                'verbose_name_plural': 'Условия',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Товар - Категория',
                'verbose_name_plural': 'Товары - Категории',
            },
        ),
        migrations.CreateModel(
            name='PromotionCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Акция - условие',
                'verbose_name_plural': 'Акции - условия',
            },
        ),
        migrations.RemoveField(
            model_name='collectionproduct',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='collectionproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='collectionproperty',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='collectionproperty',
            name='property',
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Коллекция', 'verbose_name_plural': 'Коллекции'},
        ),
        migrations.RemoveField(
            model_name='collection',
            name='calorie',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='carbohydrates',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='fats',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='image',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='name',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='price',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='product',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='property',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='proteins',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='kind',
        ),
        migrations.AddField(
            model_name='collection',
            name='child_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='api.product', verbose_name='Товар'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='is_full',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='parent_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='api.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.ManyToManyField(through='api.Collection', to='api.product'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата конца акции'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='image',
            field=models.ImageField(default=1, upload_to='promotions/images/', verbose_name='Картинка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала акции'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Загаловок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Число должно быть положительным', regex='^[0-9]+$'), api.validators.validate_less_hundred], verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.size', verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('parent_product', 'child_product'), name='unique_collection'),
        ),
        migrations.DeleteModel(
            name='CollectionProduct',
        ),
        migrations.DeleteModel(
            name='CollectionProperty',
        ),
        migrations.AddField(
            model_name='promotioncondition',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='api.condition'),
        ),
        migrations.AddField(
            model_name='promotioncondition',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='api.promotion'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.product'),
        ),
        migrations.AddField(
            model_name='categorybanner',
            name='banner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.banner'),
        ),
        migrations.AddField(
            model_name='categorybanner',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='api.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='banner',
            field=models.ManyToManyField(through='api.CategoryBanner', to='api.banner', verbose_name='Баннер'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(through='api.ProductCategory', to='api.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='condition',
            field=models.ManyToManyField(through='api.PromotionCondition', to='api.condition'),
        ),
    ]
