# Generated by Django 4.2.2 on 2023-06-22 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(validators=[django.core.validators.RegexValidator(message='Число должно быть положительным', regex='^[0-9.]+$')], verbose_name='Размер'),
        ),
    ]
