# Generated by Django 4.2.2 on 2023-06-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(default=0, max_length=255, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(default=1, max_length=255, verbose_name='Страна'),
            preserve_default=False,
        ),
    ]
