# Generated by Django 4.2.2 on 2023-06-23 12:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BucketProduct',
            new_name='BucketModification',
        ),
        migrations.RemoveField(
            model_name='bucket',
            name='product',
        ),
        migrations.RemoveField(
            model_name='bucketmodification',
            name='product',
        ),
        migrations.AddField(
            model_name='bucket',
            name='modification',
            field=models.ManyToManyField(through='api.BucketModification', to='api.modification'),
        ),
        migrations.AddField(
            model_name='bucketmodification',
            name='modification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buckets', to='api.modification', verbose_name='Товар'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modification',
            name='weight',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Число должно быть положительным', regex='^[0-9.]+$')], verbose_name='Вес'),
        ),
    ]
