# Generated by Django 4.2.2 on 2023-06-23 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_bucketproduct_bucketmodification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucket',
            old_name='modification',
            new_name='product',
        ),
    ]
