# Generated by Django 4.2.2 on 2023-06-21 11:34

import api.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_banner_category_categorybanner_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calorie',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Число должно быть положительным', regex='^[0-9.]+$')], verbose_name='Калории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbohydrates',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Число должно быть положительным', regex='^[0-9.]+$')], verbose_name='Углероды'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Число должно быть положительным', regex='^[0-9.]+$'), api.validators.validate_less_hundred], verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fats',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Число должно быть положительным', regex='^[0-9.]+$')], verbose_name='Жиры'),
        ),
        migrations.AlterField(
            model_name='product',
            name='proteins',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Число должно быть положительным', regex='^[0-9.]+$')], verbose_name='Белки'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(message='Число должно быть положительным', regex='^[0-9.]+$')], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='weight',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(message='Число должно быть положительным', regex='^[0-9.]+$')], verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='hex_color',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Неправильный формат цвета', regex='^#[a-zA-Z0-9]+$')], verbose_name='Цвет акции'),
        ),
        migrations.AlterField(
            model_name='size',
            name='measurement',
            field=models.CharField(choices=[('шт', 'T'), ('см', 'C'), ('л', 'L')], max_length=2, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(message='Число должно быть положительным', regex='^[0-9.]+$')], verbose_name='Размер'),
        ),
    ]
