# Generated by Django 4.2.2 on 2023-06-10 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_promotion_alter_product_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='hex_color',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Неправильный формат цвета', regex='^#[a-zA-Z0-9]+$')], verbose_name='Цвет акции'),
        ),
    ]
