# Generated by Django 4.2.2 on 2023-06-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_collection_alter_productproperty_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_full',
            field=models.BooleanField(default=True, verbose_name='Полный товар'),
        ),
    ]
