# Generated by Django 4.2.2 on 2023-06-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_modification_bucket_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketmodification',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
    ]
