# Generated by Django 4.2.2 on 2023-06-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_promotion_hex_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='measurement',
            field=models.CharField(choices=[('шт', 'T'), ('см', 'C'), ('default', 'D')], max_length=10, verbose_name='Единица измерения'),
        ),
    ]
