# Generated by Django 4.2.2 on 2023-06-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_size_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='measurement',
            field=models.CharField(choices=[('шт', 'T'), ('см', 'C'), ('', 'D')], max_length=2, verbose_name='Единица измерения'),
        ),
    ]
