# Generated by Django 4.2.2 on 2023-06-25 13:00

import api.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_bucketmodification_unique_bucket_modification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('emotion', models.CharField(choices=[('POSITIVE', 'Позитивный'), ('NEUTRAL', 'Нейтральный'), ('NEGATIVE', 'Негативный'), ('IDEA', 'Идея')], max_length=20, verbose_name='Эмоция')),
                ('product_quality', models.IntegerField(validators=[django.core.validators.RegexValidator(message='Число должно быть положительным', regex='^[0-9.]+$'), api.validators.validate_less_ten], verbose_name='Качество еды')),
                ('ordering', models.IntegerField(validators=[django.core.validators.RegexValidator(message='Число должно быть положительным', regex='^[0-9.]+$'), api.validators.validate_less_ten], verbose_name='Оформление заказа')),
                ('delivery_speed', models.IntegerField(validators=[django.core.validators.RegexValidator(message='Число должно быть положительным', regex='^[0-9.]+$'), api.validators.validate_less_ten], verbose_name='Скорость доставки')),
                ('order_number', models.IntegerField(validators=[django.core.validators.RegexValidator(message='Число должно быть положительным', regex='^[0-9.]+$')], verbose_name='Номер заказа')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('file', models.FileField(blank=True, null=True, upload_to='recalls/images/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AlterField(
            model_name='bucket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket', to=settings.AUTH_USER_MODEL),
        ),
    ]
