# Generated by Django 4.2.2 on 2023-06-10 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_size_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.size'),
        ),
        migrations.AlterField(
            model_name='size',
            name='measurement',
            field=models.CharField(choices=[('шт', 'T'), ('см', 'C')], default=1, max_length=2, verbose_name='Единица измерения'),
            preserve_default=False,
        ),
    ]
